### ISSUE TITLE
Rename blog to "The Valence Kjell"

### ISSUE THREAD

**Issue by clavigne** [kjelljorner/blog#2]
I'm proposing that this blog be renamed from "Street SMARTs" to "The Valence Kjell". The new name would have several advantages,

* It would teach people how to pronounce the name "Kjell".
* It's significantly more googlable. "Valence Kjell" currently returns only a few unconnected hits of other people with the name and their scientific articles. "Street smarts" however is a common sentence outside of computational chemistry. 
* In my opinion, "Street SMARTs" is too topic specific, whereas "The Valence Kjell" would be a good name for a more broad blog about chemistry with a theory / comp focus. This is important as @kjelljorner has a broad range of research interests. 
* The URL kjelljorner.github.io already contains "Kjell" but not "Street SMARTs". 
* If the blog becomes popular or if github drops free hosting, it is much easier to get [a domain name under Valence Kjell](https://domains.google.com/registrar/search?searchTerm=valence%20kjell&hl=en#) then under [street smarts](https://domains.google.com/registrar/search?searchTerm=street%20smarts%20&hl=en#).

The only disadvantage I can see IMO is that naming the blog "The Valence Kjell" may discourage potential guest contributors. It's also a silly pun but I think that's more of a neutral attribute than a true disadvantage. 

I'm willing to provide a PR if @kjelljorner is too busy.

tagging @gabegomes and @robpollice

**Comment by kjelljorner** [comment]
Closed via 45dc7b74a75a1f5d60ea3aeb6fd06222b6467408
